#!/usr/bin/env bash
set -euo pipefail

# Target-ODD adaptation dataset:
#   - map/domain: Town13, matching the local leaderboard validation missions
#   - ego: vehicle.lincoln.mkz_2020
#   - sensor rig: front_triplet_shifted only (left/front/right RGB + roof LiDAR)
#   - traffic: mixed free/normal/dense schedule in a single collection run
#
# CARLA must already be running on HOST:PORT.

CARLA_ROOT=${CARLA_ROOT:-"$HOME/dataset/byeongjae/carla-simulator"}
OUTPUT_ROOT=${OUTPUT_ROOT:-"$HOME/dataset/byeongjae/datasets/t2d_vehicle_b_front_triplet_town13_target_3h"}

HOST=${HOST:-127.0.0.1}
PORT=${PORT:-2000}
MAP=${MAP:-Town13}
VEHICLE_FILTER=${VEHICLE_FILTER:-vehicle.lincoln.mkz_2020}

PROFILES=${PROFILES:-front_triplet_shifted}
PRIMARY_PROFILE=${PRIMARY_PROFILE:-front_triplet_shifted}
COLLECTION_MODE=${COLLECTION_MODE:-paired}

EPISODES=${EPISODES:-36}
EPISODE_SEC=${EPISODE_SEC:-300}
DURATION_HOURS=${DURATION_HOURS:-3.0}

TRAFFIC_SCHEDULE=${TRAFFIC_SCHEDULE:-vehicle_b_mixed}
TRAFFIC_SCHEDULE_SEED=${TRAFFIC_SCHEDULE_SEED:-13}
TRAFFIC_VEHICLES=${TRAFFIC_VEHICLES:-60}
GLOBAL_DISTANCE_TO_LEADING_VEHICLE=${GLOBAL_DISTANCE_TO_LEADING_VEHICLE:-2.5}
GLOBAL_SPEED_DIFFERENCE=${GLOBAL_SPEED_DIFFERENCE:-0.0}
IGNORE_LIGHTS_PERCENT=${IGNORE_LIGHTS_PERCENT:-0.0}

FAIL_ON_INVALID_MOTION=${FAIL_ON_INVALID_MOTION:-1}
MIN_MOVING_RATIO=${MIN_MOVING_RATIO:-0.20}
MIN_PATH_LENGTH_M=${MIN_PATH_LENGTH_M:-100}
MIN_MOVING_SPEED_MPS=${MIN_MOVING_SPEED_MPS:-1.0}

LIDAR_FORMAT=${LIDAR_FORMAT:-npz}
OVERWRITE=${OVERWRITE:-0}

export CARLA_ROOT OUTPUT_ROOT HOST PORT MAP VEHICLE_FILTER
export PROFILES PRIMARY_PROFILE COLLECTION_MODE
export EPISODES EPISODE_SEC DURATION_HOURS
export TRAFFIC_SCHEDULE TRAFFIC_SCHEDULE_SEED TRAFFIC_VEHICLES
export GLOBAL_DISTANCE_TO_LEADING_VEHICLE GLOBAL_SPEED_DIFFERENCE IGNORE_LIGHTS_PERCENT
export FAIL_ON_INVALID_MOTION MIN_MOVING_RATIO MIN_PATH_LENGTH_M MIN_MOVING_SPEED_MPS
export LIDAR_FORMAT OVERWRITE

bash configs/collect_transfuserpp_2h.sh
