#!/usr/bin/env bash
set -euo pipefail

# Stage 1: canonical sensor input with a bounded lateral checkpoint residual.
# Unlike the navigation-route proxy, the target is the Tesla/PDM-Lite expert's
# future driven ego path, transformed into the current ego frame and resampled
# at TF++'s spatial checkpoint distances (2.5 m, then 1 m spacing).

export RUN_NAME=${RUN_NAME:-train_exact_stage1_expert_spatial_lateral_gpu1}
export TEACHER_VIEW_AS_INPUT=1

export STAGE_ADAPTER_LAYERS=all
export STAGE_ADAPTER_MODALITIES=none
export DISABLE_FUSION_ADAPTER=1
export FREEZE_ADAPTER_INCLUDE='.*'
export FEATURE_DRIFT_WEIGHT=0.0
export EXTRINSIC_AWARE=0
export SOURCE_PROFILE=tfpp_ego
export LORA_RANK=0
export LORA_ALPHA=1
export LORA_INCLUDE=''
export UNFREEZE_INCLUDE=''

export OUTPUT_RESIDUAL=1
export OUTPUT_RESIDUAL_CHECKPOINT_LATERAL_ONLY=1
export OUTPUT_RESIDUAL_HIDDEN_DIM=${OUTPUT_RESIDUAL_HIDDEN_DIM:-256}
export OUTPUT_RESIDUAL_CHECKPOINT_SCALE=${OUTPUT_RESIDUAL_CHECKPOINT_SCALE:-0.30}
export OUTPUT_RESIDUAL_SPEED_LOGIT_SCALE=0.0
export OUTPUT_RESIDUAL_GATE_BIAS=${OUTPUT_RESIDUAL_GATE_BIAS:--3.0}
export OUTPUT_RESIDUAL_DROPOUT=0.0

export ROUTE_TARGET_ONLY=1
export ROUTE_TARGET_SOURCE=future_ego_path
export ROUTE_TARGET_LEN=10
export FUTURE_EGO_MAX_HORIZON_S=${FUTURE_EGO_MAX_HORIZON_S:-6.0}
export ROUTE_LATERAL_LOSS_WEIGHT=${ROUTE_LATERAL_LOSS_WEIGHT:-1.0}
export ROUTE_HEADING_LOSS_WEIGHT=${ROUTE_HEADING_LOSS_WEIGHT:-0.25}
export ROUTE_STRAIGHT_IDENTITY_LOSS_WEIGHT=${ROUTE_STRAIGHT_IDENTITY_LOSS_WEIGHT:-0.50}
export ROUTE_TURN_GATE_LOSS_WEIGHT=${ROUTE_TURN_GATE_LOSS_WEIGHT:-0.20}
export ROUTE_TURN_LATERAL_THRESHOLD_M=${ROUTE_TURN_LATERAL_THRESHOLD_M:-0.50}
export ROUTE_TURN_ANGLE_THRESHOLD_RAD=${ROUTE_TURN_ANGLE_THRESHOLD_RAD:-0.08}

export CONTROL_LOSS_WEIGHT=0.0
export STOP_STATE_AUX_LOSS_WEIGHT=0.0
export STOP_REASON_AUX_LOSS_WEIGHT=0.0
export OUTPUT_PRIOR_XY_LOSS_WEIGHT=0.0
export OUTPUT_PRIOR_SPEED_LOSS_WEIGHT=0.0
export PDM_BEHAVIOR_LOSS_WEIGHT=0.0
export PDM_LATERAL_LOSS_WEIGHT=0.0
export PDM_CONTROLLER_LOSS_WEIGHT=0.0
export PDM_PLAN_STEER_LOSS_WEIGHT=0.0
export PDM_PLAN_THROTTLE_LOSS_WEIGHT=0.0
export PDM_PLAN_BRAKE_LOSS_WEIGHT=0.0

export SELECTION_METRIC=${SELECTION_METRIC:-loss}
export LR=${LR:-1.0e-5}
export BATCH_SIZE=${BATCH_SIZE:-24}
export NUM_WORKERS=${NUM_WORKERS:-4}
export EPOCHS=${EPOCHS:-10}
export EARLY_STOP_PATIENCE=${EARLY_STOP_PATIENCE:-3}

exec "$(dirname "$0")/train_exact_target_only_dl2.sh"
