#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

# Town13 expert imitation, v7.
# v6 recovered launch/release but overcorrected: stop/hazard frames predicted
# too much speed and the direct longitudinal head often missed required brake.
# This preset fine-tunes from v6 and adds explicit stop speed ceilings plus
# brake true-positive losses, while keeping release_go non-stop supervision.

export DATA_ROOT=${DATA_ROOT:-"$HOME/dataset/byeongjae/datasets/t2d_vehicle_b_front_triplet_town13_target_3h"}
export WORK_ROOT=${WORK_ROOT:-"$HOME/teach2drive/runs/tfpp_vehicle_b_front_triplet_town13_expert_v1"}
export OUT=${OUT:-"$HOME/teach2drive/runs/tfpp_vehicle_b_front_triplet_town13_expert_v7_balanced_release_stop/train_front_triplet_shifted_town13_expert_v7_balanced_release_stop"}
export INIT_CHECKPOINT=${INIT_CHECKPOINT:-"$HOME/teach2drive/runs/tfpp_vehicle_b_front_triplet_town13_expert_v6_release_recovery/train_front_triplet_shifted_town13_expert_v6_release_recovery/best_model.pt"}

export CAMERAS=${CAMERAS:-left,front,right}
export EPOCHS=${EPOCHS:-60}
export EARLY_STOP_PATIENCE=${EARLY_STOP_PATIENCE:-15}
export BATCH_SIZE=${BATCH_SIZE:-128}
export CACHE_BATCH_SIZE=${CACHE_BATCH_SIZE:-128}
export DATA_PARALLEL=${DATA_PARALLEL:-1}
export OVERWRITE=${OVERWRITE:-0}
export LR=${LR:-3e-5}
export WEIGHT_DECAY=${WEIGHT_DECAY:-1e-4}

export MOVING_SAMPLE_WEIGHT=${MOVING_SAMPLE_WEIGHT:-1.10}
export STOPPED_SAMPLE_WEIGHT=${STOPPED_SAMPLE_WEIGHT:-1.15}
export HAZARD_SAMPLE_WEIGHT=${HAZARD_SAMPLE_WEIGHT:-2.5}

export XY_LOSS_WEIGHT=${XY_LOSS_WEIGHT:-0.9}
export YAW_LOSS_WEIGHT=${YAW_LOSS_WEIGHT:-0.03}
export SPEED_LOSS_WEIGHT=${SPEED_LOSS_WEIGHT:-1.25}
export SPEED_FLOOR_MASK=${SPEED_FLOOR_MASK:-target}
export SPEED_FLOOR_TARGET_THRESHOLD=${SPEED_FLOOR_TARGET_THRESHOLD:-1.8}
export SPEED_FLOOR_LOSS_WEIGHT=${SPEED_FLOOR_LOSS_WEIGHT:-0.04}
export SPEED_FLOOR_MPS=${SPEED_FLOOR_MPS:-1.2}

# Counterbalance v6's false-go behavior on stop/hazard frames.
export STOP_SPEED_TARGET_THRESHOLD=${STOP_SPEED_TARGET_THRESHOLD:-0.5}
export STOP_SPEED_CEILING_MPS=${STOP_SPEED_CEILING_MPS:-0.5}
export STOP_SPEED_CEILING_LOSS_WEIGHT=${STOP_SPEED_CEILING_LOSS_WEIGHT:-1.0}
export HAZARD_STOP_SPEED_CEILING_LOSS_WEIGHT=${HAZARD_STOP_SPEED_CEILING_LOSS_WEIGHT:-2.0}

export LAUNCH_CURRENT_SPEED_THRESHOLD=${LAUNCH_CURRENT_SPEED_THRESHOLD:-1.0}
export LAUNCH_TARGET_SPEED_THRESHOLD=${LAUNCH_TARGET_SPEED_THRESHOLD:-1.0}
export LAUNCH_SAMPLE_WEIGHT=${LAUNCH_SAMPLE_WEIGHT:-3.0}
export LAUNCH_SPEED_FLOOR_LOSS_WEIGHT=${LAUNCH_SPEED_FLOOR_LOSS_WEIGHT:-0.20}
export LAUNCH_SPEED_FLOOR_MPS=${LAUNCH_SPEED_FLOOR_MPS:-2.0}
export LAUNCH_STOP_NEGATIVE=${LAUNCH_STOP_NEGATIVE:-1}

export RELEASE_TARGET_SPEED_THRESHOLD=${RELEASE_TARGET_SPEED_THRESHOLD:-1.0}
export RELEASE_SAMPLE_WEIGHT=${RELEASE_SAMPLE_WEIGHT:-4.0}
export RELEASE_SPEED_FLOOR_LOSS_WEIGHT=${RELEASE_SPEED_FLOOR_LOSS_WEIGHT:-0.35}
export RELEASE_SPEED_FLOOR_MPS=${RELEASE_SPEED_FLOOR_MPS:-2.0}
export RELEASE_STOP_NEGATIVE=${RELEASE_STOP_NEGATIVE:-1}

export SPEED_DELTA_LOSS_WEIGHT=${SPEED_DELTA_LOSS_WEIGHT:-0.08}
export SPEED_CURVATURE_LOSS_WEIGHT=${SPEED_CURVATURE_LOSS_WEIGHT:-0.03}
export TRAJ_DELTA_LOSS_WEIGHT=${TRAJ_DELTA_LOSS_WEIGHT:-0.04}
export TRAJ_CURVATURE_LOSS_WEIGHT=${TRAJ_CURVATURE_LOSS_WEIGHT:-0.02}
export PRIOR_LOSS_WEIGHT=${PRIOR_LOSS_WEIGHT:-0.005}

# Hybrid inference uses PID steering; keep direct control focused on throttle
# and brake. v7 restores brake true positives while preserving launch/release
# no-brake constraints from v6.
export CONTROL_LOSS_WEIGHT=${CONTROL_LOSS_WEIGHT:-0.40}
export CONTROL_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT=${CONTROL_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT:-1.0}
export CONTROL_LAUNCH_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT=${CONTROL_LAUNCH_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT:-5.0}
export CONTROL_LAUNCH_THROTTLE_FLOOR_LOSS_WEIGHT=${CONTROL_LAUNCH_THROTTLE_FLOOR_LOSS_WEIGHT:-3.0}
export CONTROL_RELEASE_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT=${CONTROL_RELEASE_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT:-7.0}
export CONTROL_RELEASE_THROTTLE_FLOOR_LOSS_WEIGHT=${CONTROL_RELEASE_THROTTLE_FLOOR_LOSS_WEIGHT:-5.0}
export CONTROL_BRAKE_TRUE_POSITIVE_LOSS_WEIGHT=${CONTROL_BRAKE_TRUE_POSITIVE_LOSS_WEIGHT:-4.0}
export CONTROL_HAZARD_BRAKE_TRUE_POSITIVE_LOSS_WEIGHT=${CONTROL_HAZARD_BRAKE_TRUE_POSITIVE_LOSS_WEIGHT:-8.0}
export CONTROL_BRAKE_OFF_MAX=${CONTROL_BRAKE_OFF_MAX:-0.08}
export CONTROL_BRAKE_ON_MIN=${CONTROL_BRAKE_ON_MIN:-0.35}
export CONTROL_BRAKE_ON_TARGET_THRESHOLD=${CONTROL_BRAKE_ON_TARGET_THRESHOLD:-0.20}
export CONTROL_LAUNCH_THROTTLE_FLOOR=${CONTROL_LAUNCH_THROTTLE_FLOOR:-0.28}
export CONTROL_RELEASE_THROTTLE_FLOOR=${CONTROL_RELEASE_THROTTLE_FLOOR:-0.32}
export CONTROL_NO_BRAKE_TARGET_THRESHOLD=${CONTROL_NO_BRAKE_TARGET_THRESHOLD:-0.12}

export STOP_LOSS_AFTER_EPOCH=${STOP_LOSS_AFTER_EPOCH:-1}
export STOP_LOSS_WEIGHT=${STOP_LOSS_WEIGHT:-0.08}
export STOP_STATE_LOSS_WEIGHT=${STOP_STATE_LOSS_WEIGHT:-0.10}
export STOP_REASON_LOSS_WEIGHT=${STOP_REASON_LOSS_WEIGHT:-0.05}
export STOP_POSITIVE_LOSS_SCALE=${STOP_POSITIVE_LOSS_SCALE:-1.5}
export STOP_NEGATIVE_LOSS_SCALE=${STOP_NEGATIVE_LOSS_SCALE:-1.0}

export SPEED_TEACHER_BLEND=${SPEED_TEACHER_BLEND:-0.0}
export SPEED_DISTILL_LOSS_WEIGHT=${SPEED_DISTILL_LOSS_WEIGHT:-0.0}

exec bash configs/train_tfpp_vehicle_b_expert_v1_server.sh
