#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

# Feature+Fusion+Output Adapter v1.
#
# Stage 1 is the already trained feature-then-fusion adapter:
#   shifted sensor features -> canonical-like fusion features
#
# This preset freezes that adapter while caching the TransFuser++ prior, then
# trains a fresh conservative output-level policy adapter on the same paired
# dataset used by the feature/fusion adapters. This keeps the experiment family
# comparable to Feature Adapter v1 / Fusion Adapter v1, instead of mixing in the
# later Town13 Vehicle-B output-adapter dataset from v1-v7.

export DATA_ROOT=${DATA_ROOT:-"$HOME/dataset/byeongjae/datasets/t2d_transfuserpp_paired_24ep_motion_safe"}
export WORK_ROOT=${WORK_ROOT:-"$HOME/teach2drive/runs/tfpp_feature_then_fusion_output_adapter_v1"}
export OUT=${OUT:-"$WORK_ROOT/train_front_triplet_shifted_feature_then_fusion_output_adapter_v1"}
export FEATURE_THEN_FUSION_ADAPTER_CHECKPOINT=${FEATURE_THEN_FUSION_ADAPTER_CHECKPOINT:-"$HOME/dataset/byeongjae/runs/tfpp_feature_then_fusion_adapter_v1/train_feature_then_fusion_adapter_v1/best_model.pt"}

export CAMERAS=${CAMERAS:-left,front,right}
export EPOCHS=${EPOCHS:-80}
export EARLY_STOP_PATIENCE=${EARLY_STOP_PATIENCE:-15}
export BATCH_SIZE=${BATCH_SIZE:-128}
export CACHE_BATCH_SIZE=${CACHE_BATCH_SIZE:-128}
export DATA_PARALLEL=${DATA_PARALLEL:-1}

# The feature-then-fusion adapter is patched into the frozen TransFuser++
# backbone during prior caching. Keep caching on one CUDA device to avoid
# DataParallel closure/device mismatch; use multi-GPU for output adapter
# training after the cache is built.
export CACHE_DATA_PARALLEL=${CACHE_DATA_PARALLEL:-0}
export TRAIN_DATA_PARALLEL=${TRAIN_DATA_PARALLEL:-$DATA_PARALLEL}
export OVERWRITE=${OVERWRITE:-0}

export STAGE_FEATURE_ADAPTER_BLEND=${STAGE_FEATURE_ADAPTER_BLEND:-1.0}
export FUSION_ADAPTER_BLEND=${FUSION_ADAPTER_BLEND:-1.0}

export MOVING_SAMPLE_WEIGHT=${MOVING_SAMPLE_WEIGHT:-1.10}
export STOPPED_SAMPLE_WEIGHT=${STOPPED_SAMPLE_WEIGHT:-1.00}
export HAZARD_SAMPLE_WEIGHT=${HAZARD_SAMPLE_WEIGHT:-1.50}

export XY_LOSS_WEIGHT=${XY_LOSS_WEIGHT:-1.0}
export YAW_LOSS_WEIGHT=${YAW_LOSS_WEIGHT:-0.05}
export SPEED_LOSS_WEIGHT=${SPEED_LOSS_WEIGHT:-0.60}
export SPEED_FLOOR_MASK=${SPEED_FLOOR_MASK:-target}
export SPEED_FLOOR_TARGET_THRESHOLD=${SPEED_FLOOR_TARGET_THRESHOLD:-2.0}
export SPEED_FLOOR_LOSS_WEIGHT=${SPEED_FLOOR_LOSS_WEIGHT:-0.05}
export SPEED_FLOOR_MPS=${SPEED_FLOOR_MPS:-1.0}

export LAUNCH_CURRENT_SPEED_THRESHOLD=${LAUNCH_CURRENT_SPEED_THRESHOLD:-0.8}
export LAUNCH_TARGET_SPEED_THRESHOLD=${LAUNCH_TARGET_SPEED_THRESHOLD:-2.0}
export LAUNCH_SAMPLE_WEIGHT=${LAUNCH_SAMPLE_WEIGHT:-1.20}
export LAUNCH_SPEED_FLOOR_LOSS_WEIGHT=${LAUNCH_SPEED_FLOOR_LOSS_WEIGHT:-0.05}
export LAUNCH_SPEED_FLOOR_MPS=${LAUNCH_SPEED_FLOOR_MPS:-1.5}
export LAUNCH_STOP_NEGATIVE=${LAUNCH_STOP_NEGATIVE:-0}

export RELEASE_TARGET_SPEED_THRESHOLD=${RELEASE_TARGET_SPEED_THRESHOLD:-1.0}
export RELEASE_SAMPLE_WEIGHT=${RELEASE_SAMPLE_WEIGHT:-1.20}
export RELEASE_SPEED_FLOOR_LOSS_WEIGHT=${RELEASE_SPEED_FLOOR_LOSS_WEIGHT:-0.05}
export RELEASE_SPEED_FLOOR_MPS=${RELEASE_SPEED_FLOOR_MPS:-1.5}
export RELEASE_STOP_NEGATIVE=${RELEASE_STOP_NEGATIVE:-0}

export SPEED_DELTA_LOSS_WEIGHT=${SPEED_DELTA_LOSS_WEIGHT:-0.08}
export SPEED_CURVATURE_LOSS_WEIGHT=${SPEED_CURVATURE_LOSS_WEIGHT:-0.03}
export TRAJ_DELTA_LOSS_WEIGHT=${TRAJ_DELTA_LOSS_WEIGHT:-0.05}
export TRAJ_CURVATURE_LOSS_WEIGHT=${TRAJ_CURVATURE_LOSS_WEIGHT:-0.02}

# Keep the output adapter close to the stronger feature+fusion prior.
export PRIOR_LOSS_WEIGHT=${PRIOR_LOSS_WEIGHT:-0.08}

export CONTROL_LOSS_WEIGHT=${CONTROL_LOSS_WEIGHT:-0.25}
export CONTROL_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT=${CONTROL_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT:-0.50}
export CONTROL_LAUNCH_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT=${CONTROL_LAUNCH_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT:-0.75}
export CONTROL_LAUNCH_THROTTLE_FLOOR_LOSS_WEIGHT=${CONTROL_LAUNCH_THROTTLE_FLOOR_LOSS_WEIGHT:-0.25}
export CONTROL_RELEASE_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT=${CONTROL_RELEASE_BRAKE_FALSE_POSITIVE_LOSS_WEIGHT:-0.50}
export CONTROL_RELEASE_THROTTLE_FLOOR_LOSS_WEIGHT=${CONTROL_RELEASE_THROTTLE_FLOOR_LOSS_WEIGHT:-0.25}
export CONTROL_BRAKE_TRUE_POSITIVE_LOSS_WEIGHT=${CONTROL_BRAKE_TRUE_POSITIVE_LOSS_WEIGHT:-0.25}
export CONTROL_HAZARD_BRAKE_TRUE_POSITIVE_LOSS_WEIGHT=${CONTROL_HAZARD_BRAKE_TRUE_POSITIVE_LOSS_WEIGHT:-0.25}
export CONTROL_BRAKE_OFF_MAX=${CONTROL_BRAKE_OFF_MAX:-0.10}
export CONTROL_LAUNCH_THROTTLE_FLOOR=${CONTROL_LAUNCH_THROTTLE_FLOOR:-0.20}
export CONTROL_RELEASE_THROTTLE_FLOOR=${CONTROL_RELEASE_THROTTLE_FLOOR:-0.20}
export CONTROL_NO_BRAKE_TARGET_THRESHOLD=${CONTROL_NO_BRAKE_TARGET_THRESHOLD:-0.10}

# Do not use stop classifiers as a behavior lever in this first combined run.
export STOP_LOSS_AFTER_EPOCH=${STOP_LOSS_AFTER_EPOCH:-9999}
export STOP_LOSS_WEIGHT=${STOP_LOSS_WEIGHT:-0.0}
export STOP_STATE_LOSS_WEIGHT=${STOP_STATE_LOSS_WEIGHT:-0.0}
export STOP_REASON_LOSS_WEIGHT=${STOP_REASON_LOSS_WEIGHT:-0.0}

export SPEED_TEACHER_BLEND=${SPEED_TEACHER_BLEND:-0.0}
export SPEED_DISTILL_LOSS_WEIGHT=${SPEED_DISTILL_LOSS_WEIGHT:-0.0}

exec bash configs/train_tfpp_vehicle_b_expert_v1_server.sh
