#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

VARIANT="${VARIANT:-feature}"
COMMON_VIEW_ROOT="/home/jovyan/dataset/byeongjae/runs/tfpp_tesla_town13_peft_expert_bc_prior_smooth_sgpu/profile_views"
COMMON_INDEX_DIR="/home/jovyan/dataset/byeongjae/runs/tfpp_tesla_town13_peft_expert_bc_prior_smooth_sgpu/indexes"

export SNAPSHOT_COMPLETE_EPISODES="${SNAPSHOT_COMPLETE_EPISODES:-0}"
export REFRESH_SNAPSHOT="${REFRESH_SNAPSHOT:-0}"
export SKIP_EXPORT="${SKIP_EXPORT:-1}"
export EXPORT_OVERWRITE="${EXPORT_OVERWRITE:-0}"
export INDEX_OVERWRITE="${INDEX_OVERWRITE:-0}"
export OVERWRITE="${OVERWRITE:-1}"
export TARGET_VIEW="${TARGET_VIEW:-${COMMON_VIEW_ROOT}/front_triplet_shifted}"
export TARGET_INDEX="${TARGET_INDEX:-${COMMON_INDEX_DIR}/front_triplet_shifted_index.npz}"

export EPOCHS="${EPOCHS:-20}"
export EARLY_STOP_PATIENCE="${EARLY_STOP_PATIENCE:-6}"
export BATCH_SIZE="${BATCH_SIZE:-8}"
export NUM_WORKERS="${NUM_WORKERS:-4}"
export TRAJ_SMOOTH_LOSS_WEIGHT="${TRAJ_SMOOTH_LOSS_WEIGHT:-0.0}"
export SPEED_SMOOTH_LOSS_WEIGHT="${SPEED_SMOOTH_LOSS_WEIGHT:-0.0}"
export STOP_SPEED_CEILING_MPS="${STOP_SPEED_CEILING_MPS:-0.45}"

case "$VARIANT" in
  feature)
    RUN_NAME="${RUN_NAME:-prior_feature_only_g0}"
    export LR="${LR:-1e-5}"
    export LORA_RANK="${LORA_RANK:-0}"
    export STAGE_FEATURE_ADAPTER_BLEND="${STAGE_FEATURE_ADAPTER_BLEND:-0.55}"
    export FUSION_ADAPTER_BLEND="${FUSION_ADAPTER_BLEND:-0.55}"
    export FEATURE_DRIFT_LOSS_WEIGHT="${FEATURE_DRIFT_LOSS_WEIGHT:-0.35}"
    export OUTPUT_PRIOR_XY_LOSS_WEIGHT="${OUTPUT_PRIOR_XY_LOSS_WEIGHT:-0.20}"
    export OUTPUT_PRIOR_SPEED_LOSS_WEIGHT="${OUTPUT_PRIOR_SPEED_LOSS_WEIGHT:-0.35}"
    export HAZARD_SAMPLE_WEIGHT="${HAZARD_SAMPLE_WEIGHT:-4.0}"
    export STOP_SPEED_CEILING_LOSS_WEIGHT="${STOP_SPEED_CEILING_LOSS_WEIGHT:-0.80}"
    export SPEED_LOSS_WEIGHT="${SPEED_LOSS_WEIGHT:-0.75}"
    export STOP_LOSS_WEIGHT="${STOP_LOSS_WEIGHT:-0.08}"
    ;;
  lora2)
    RUN_NAME="${RUN_NAME:-prior_lora2_g1}"
    export LR="${LR:-8e-6}"
    export LORA_RANK="${LORA_RANK:-2}"
    export LORA_ALPHA="${LORA_ALPHA:-4.0}"
    export LORA_DROPOUT="${LORA_DROPOUT:-0.02}"
    export STAGE_FEATURE_ADAPTER_BLEND="${STAGE_FEATURE_ADAPTER_BLEND:-0.65}"
    export FUSION_ADAPTER_BLEND="${FUSION_ADAPTER_BLEND:-0.65}"
    export FEATURE_DRIFT_LOSS_WEIGHT="${FEATURE_DRIFT_LOSS_WEIGHT:-0.25}"
    export OUTPUT_PRIOR_XY_LOSS_WEIGHT="${OUTPUT_PRIOR_XY_LOSS_WEIGHT:-0.12}"
    export OUTPUT_PRIOR_SPEED_LOSS_WEIGHT="${OUTPUT_PRIOR_SPEED_LOSS_WEIGHT:-0.45}"
    export HAZARD_SAMPLE_WEIGHT="${HAZARD_SAMPLE_WEIGHT:-5.0}"
    export STOP_SPEED_CEILING_LOSS_WEIGHT="${STOP_SPEED_CEILING_LOSS_WEIGHT:-0.90}"
    export SPEED_LOSS_WEIGHT="${SPEED_LOSS_WEIGHT:-0.85}"
    export STOP_LOSS_WEIGHT="${STOP_LOSS_WEIGHT:-0.10}"
    ;;
  lora4)
    RUN_NAME="${RUN_NAME:-prior_lora4_g2}"
    export LR="${LR:-1e-5}"
    export LORA_RANK="${LORA_RANK:-4}"
    export LORA_ALPHA="${LORA_ALPHA:-8.0}"
    export LORA_DROPOUT="${LORA_DROPOUT:-0.02}"
    export STAGE_FEATURE_ADAPTER_BLEND="${STAGE_FEATURE_ADAPTER_BLEND:-0.65}"
    export FUSION_ADAPTER_BLEND="${FUSION_ADAPTER_BLEND:-0.65}"
    export FEATURE_DRIFT_LOSS_WEIGHT="${FEATURE_DRIFT_LOSS_WEIGHT:-0.22}"
    export OUTPUT_PRIOR_XY_LOSS_WEIGHT="${OUTPUT_PRIOR_XY_LOSS_WEIGHT:-0.10}"
    export OUTPUT_PRIOR_SPEED_LOSS_WEIGHT="${OUTPUT_PRIOR_SPEED_LOSS_WEIGHT:-0.30}"
    export HAZARD_SAMPLE_WEIGHT="${HAZARD_SAMPLE_WEIGHT:-4.5}"
    export STOP_SPEED_CEILING_LOSS_WEIGHT="${STOP_SPEED_CEILING_LOSS_WEIGHT:-0.80}"
    export SPEED_LOSS_WEIGHT="${SPEED_LOSS_WEIGHT:-0.80}"
    export STOP_LOSS_WEIGHT="${STOP_LOSS_WEIGHT:-0.09}"
    ;;
  strict)
    RUN_NAME="${RUN_NAME:-prior_strict_g3}"
    export LR="${LR:-6e-6}"
    export LORA_RANK="${LORA_RANK:-2}"
    export LORA_ALPHA="${LORA_ALPHA:-4.0}"
    export LORA_DROPOUT="${LORA_DROPOUT:-0.02}"
    export STAGE_FEATURE_ADAPTER_BLEND="${STAGE_FEATURE_ADAPTER_BLEND:-0.45}"
    export FUSION_ADAPTER_BLEND="${FUSION_ADAPTER_BLEND:-0.45}"
    export FEATURE_DRIFT_LOSS_WEIGHT="${FEATURE_DRIFT_LOSS_WEIGHT:-0.40}"
    export OUTPUT_PRIOR_XY_LOSS_WEIGHT="${OUTPUT_PRIOR_XY_LOSS_WEIGHT:-0.30}"
    export OUTPUT_PRIOR_SPEED_LOSS_WEIGHT="${OUTPUT_PRIOR_SPEED_LOSS_WEIGHT:-0.55}"
    export HAZARD_SAMPLE_WEIGHT="${HAZARD_SAMPLE_WEIGHT:-5.0}"
    export STOP_SPEED_CEILING_LOSS_WEIGHT="${STOP_SPEED_CEILING_LOSS_WEIGHT:-1.00}"
    export SPEED_LOSS_WEIGHT="${SPEED_LOSS_WEIGHT:-0.75}"
    export STOP_LOSS_WEIGHT="${STOP_LOSS_WEIGHT:-0.10}"
    ;;
  *)
    echo "unknown VARIANT=$VARIANT" >&2
    exit 2
    ;;
esac

export WORK_ROOT="${WORK_ROOT:-/home/jovyan/dataset/byeongjae/runs/tfpp_tesla_town13_${RUN_NAME}}"
export OUT="${OUT:-${WORK_ROOT}/train_front_triplet_shifted_${RUN_NAME}}"

echo "=== prior residual variant"
echo "VARIANT=$VARIANT"
echo "RUN_NAME=$RUN_NAME"
echo "CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-}"
echo "WORK_ROOT=$WORK_ROOT"
echo "OUT=$OUT"
echo "TARGET_VIEW=$TARGET_VIEW"
echo "TARGET_INDEX=$TARGET_INDEX"
echo "LR=$LR LORA_RANK=$LORA_RANK blend=$STAGE_FEATURE_ADAPTER_BLEND/$FUSION_ADAPTER_BLEND"
echo "prior=$OUTPUT_PRIOR_XY_LOSS_WEIGHT/$OUTPUT_PRIOR_SPEED_LOSS_WEIGHT drift=$FEATURE_DRIFT_LOSS_WEIGHT hazard=$HAZARD_SAMPLE_WEIGHT"

exec bash configs/train_tfpp_tesla_town13_task_feature_adapter_server.sh
